/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppCliAuthRouteImport } from './routes/_app/cli-auth'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppVoicesRouteImport } from './routes/_app/voices'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as ShareSessionIdRouteImport } from './routes/share.$sessionId'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminGeneralRouteImport } from './routes/_app/admin/general'
import { Route as AppAdminModelsRouteImport } from './routes/_app/admin/models'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminInferenceServersIndexRouteImport } from './routes/_app/admin/inference-servers.index'
import { Route as AppAdminInferenceServersServerIdRouteImport } from './routes/_app/admin/inference-servers.$serverId'
import { Route as AppAdminModelsIndexRouteImport } from './routes/_app/admin/models/index'
import { Route as AppAdminModelsFamilyRouteImport } from './routes/_app/admin/models/$family'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCliAuthRoute = AppCliAuthRouteImport.update({
  id: '/cli-auth',
  path: '/cli-auth',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVoicesRoute = AppVoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const ShareSessionIdRoute = ShareSessionIdRouteImport.update({
  id: '/share/$sessionId',
  path: '/share/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminGeneralRoute = AppAdminGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminModelsRoute = AppAdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminInferenceServersIndexRoute =
  AppAdminInferenceServersIndexRouteImport.update({
    id: '/inference-servers/',
    path: '/inference-servers/',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminInferenceServersServerIdRoute =
  AppAdminInferenceServersServerIdRouteImport.update({
    id: '/inference-servers/$serverId',
    path: '/inference-servers/$serverId',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminModelsIndexRoute = AppAdminModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminModelsRoute,
} as any)
const AppAdminModelsFamilyRoute = AppAdminModelsFamilyRouteImport.update({
  id: '/$family',
  path: '/$family',
  getParentRoute: () => AppAdminModelsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/cli-auth': typeof AppCliAuthRoute
  '/history': typeof AppHistoryRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/voices': typeof AppVoicesRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/share/$sessionId': typeof ShareSessionIdRoute
  '/admin/general': typeof AppAdminGeneralRoute
  '/admin/models': typeof AppAdminModelsRouteWithChildren
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/': typeof AppAdminIndexRoute
  '/admin/inference-servers/$serverId': typeof AppAdminInferenceServersServerIdRoute
  '/admin/models/$family': typeof AppAdminModelsFamilyRoute
  '/admin/inference-servers/': typeof AppAdminInferenceServersIndexRoute
  '/admin/models/': typeof AppAdminModelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/setup': typeof SetupRoute
  '/cli-auth': typeof AppCliAuthRoute
  '/history': typeof AppHistoryRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/voices': typeof AppVoicesRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/share/$sessionId': typeof ShareSessionIdRoute
  '/admin/general': typeof AppAdminGeneralRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin': typeof AppAdminIndexRoute
  '/admin/inference-servers/$serverId': typeof AppAdminInferenceServersServerIdRoute
  '/admin/models/$family': typeof AppAdminModelsFamilyRoute
  '/admin/inference-servers': typeof AppAdminInferenceServersIndexRoute
  '/admin/models': typeof AppAdminModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/setup': typeof SetupRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/cli-auth': typeof AppCliAuthRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/voices': typeof AppVoicesRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/share/$sessionId': typeof ShareSessionIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/general': typeof AppAdminGeneralRoute
  '/_app/admin/models': typeof AppAdminModelsRouteWithChildren
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/admin/inference-servers/$serverId': typeof AppAdminInferenceServersServerIdRoute
  '/_app/admin/models/$family': typeof AppAdminModelsFamilyRoute
  '/_app/admin/inference-servers/': typeof AppAdminInferenceServersIndexRoute
  '/_app/admin/models/': typeof AppAdminModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/admin'
    | '/cli-auth'
    | '/history'
    | '/profile'
    | '/settings'
    | '/voices'
    | '/login'
    | '/register'
    | '/share/$sessionId'
    | '/admin/general'
    | '/admin/models'
    | '/admin/users'
    | '/admin/'
    | '/admin/inference-servers/$serverId'
    | '/admin/models/$family'
    | '/admin/inference-servers/'
    | '/admin/models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/cli-auth'
    | '/history'
    | '/profile'
    | '/settings'
    | '/voices'
    | '/login'
    | '/register'
    | '/share/$sessionId'
    | '/admin/general'
    | '/admin/users'
    | '/admin'
    | '/admin/inference-servers/$serverId'
    | '/admin/models/$family'
    | '/admin/inference-servers'
    | '/admin/models'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/setup'
    | '/_app/admin'
    | '/_app/cli-auth'
    | '/_app/history'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/voices'
    | '/_auth/login'
    | '/_auth/register'
    | '/share/$sessionId'
    | '/_app/'
    | '/_app/admin/general'
    | '/_app/admin/models'
    | '/_app/admin/users'
    | '/_app/admin/'
    | '/_app/admin/inference-servers/$serverId'
    | '/_app/admin/models/$family'
    | '/_app/admin/inference-servers/'
    | '/_app/admin/models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SetupRoute: typeof SetupRoute
  ShareSessionIdRoute: typeof ShareSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cli-auth': {
      id: '/_app/cli-auth'
      path: '/cli-auth'
      fullPath: '/cli-auth'
      preLoaderRoute: typeof AppCliAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voices': {
      id: '/_app/voices'
      path: '/voices'
      fullPath: '/voices'
      preLoaderRoute: typeof AppVoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/share/$sessionId': {
      id: '/share/$sessionId'
      path: '/share/$sessionId'
      fullPath: '/share/$sessionId'
      preLoaderRoute: typeof ShareSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/general': {
      id: '/_app/admin/general'
      path: '/general'
      fullPath: '/admin/general'
      preLoaderRoute: typeof AppAdminGeneralRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/models': {
      id: '/_app/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AppAdminModelsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/inference-servers/': {
      id: '/_app/admin/inference-servers/'
      path: '/inference-servers'
      fullPath: '/admin/inference-servers/'
      preLoaderRoute: typeof AppAdminInferenceServersIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/inference-servers/$serverId': {
      id: '/_app/admin/inference-servers/$serverId'
      path: '/inference-servers/$serverId'
      fullPath: '/admin/inference-servers/$serverId'
      preLoaderRoute: typeof AppAdminInferenceServersServerIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/models/': {
      id: '/_app/admin/models/'
      path: '/'
      fullPath: '/admin/models/'
      preLoaderRoute: typeof AppAdminModelsIndexRouteImport
      parentRoute: typeof AppAdminModelsRoute
    }
    '/_app/admin/models/$family': {
      id: '/_app/admin/models/$family'
      path: '/$family'
      fullPath: '/admin/models/$family'
      preLoaderRoute: typeof AppAdminModelsFamilyRouteImport
      parentRoute: typeof AppAdminModelsRoute
    }
  }
}

interface AppAdminModelsRouteChildren {
  AppAdminModelsFamilyRoute: typeof AppAdminModelsFamilyRoute
  AppAdminModelsIndexRoute: typeof AppAdminModelsIndexRoute
}

const AppAdminModelsRouteChildren: AppAdminModelsRouteChildren = {
  AppAdminModelsFamilyRoute: AppAdminModelsFamilyRoute,
  AppAdminModelsIndexRoute: AppAdminModelsIndexRoute,
}

const AppAdminModelsRouteWithChildren = AppAdminModelsRoute._addFileChildren(
  AppAdminModelsRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminGeneralRoute: typeof AppAdminGeneralRoute
  AppAdminModelsRoute: typeof AppAdminModelsRouteWithChildren
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminInferenceServersServerIdRoute: typeof AppAdminInferenceServersServerIdRoute
  AppAdminInferenceServersIndexRoute: typeof AppAdminInferenceServersIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminGeneralRoute: AppAdminGeneralRoute,
  AppAdminModelsRoute: AppAdminModelsRouteWithChildren,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminInferenceServersServerIdRoute: AppAdminInferenceServersServerIdRoute,
  AppAdminInferenceServersIndexRoute: AppAdminInferenceServersIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCliAuthRoute: typeof AppCliAuthRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVoicesRoute: typeof AppVoicesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCliAuthRoute: AppCliAuthRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVoicesRoute: AppVoicesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SetupRoute: SetupRoute,
  ShareSessionIdRoute: ShareSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
